# Generated by Django 4.1.5 on 2023-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reciept',
            field=models.FileField(null=True, upload_to='orders/reciepts/'),
        ),
    ]
