# Generated by Django 4.1.5 on 2023-08-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reciept',
            field=models.FileField(blank=True, null=True, upload_to='orders/reciepts/'),
        ),
    ]
